### ISSUE TITLE
bootstrapping oxcalSumSim

### ISSUE THREAD

**Issue by vogelso** [ISAAKiel/r_tutorial_caa_2018#3]
Dear ISAAK team,

bootstrapping the oxcalSumSim() do() call (part "Using simulations to qualify sum calibration") fails with error: 'argument "theta" is missing'. I used the bootstrap package as it provides the bootstrap() function used in the script. Acording to he bootstrap help, "theta" is the function to be bootstrapped. Am I using the wrong bootstrap package or is there an issue in the way oxcalSumSim is bootstrapped in the script?

`sim_result <- bawue_final %>% bootstrap(10) %>% do(
  oxcalSumSim(
    n = nrow(bawue_final),
    stds = sample(bawue_final$c14std),
    timeframe_begin = -5500,
    timeframe_end = -700,
    date_distribution = "uniform"
  )$raw_probabilities
)`

Many thanks,
Oliver

**Comment by MartinHinz** [comment]
Thanks for the message! Will check that out asap, admittedly have not tried bootstrap with oxcAAR yet. But can do that next week the earliest, sorry.

**Comment by vogelso** [comment]
Great! Well, it does not need to be bootstrap though. Any other way to run a series of simulations would be wonderful. The rcarbon package e.g. has a series of tools to run Monte Carlo simulations which work quite well (e.g. binsense,binPrep,modelTest).

**Comment by MartinHinz** [comment]
You might have a look to our tutorial that we had on CAA 2018:

https://github.com/ISAAKiel/r_tutorial_caa_2018

More precise to script 3, where I describe Monte Carlo Simulation using our package:

https://github.com/ISAAKiel/r_tutorial_caa_2018/blob/master/scripts/third_part_mass_operations.md

Actually, when reviewing this, I realise that I have used bootstrap there!?

**Comment by vogelso** [comment]
Yes, you used bootstrap there :-)

The latter script from CAA 2018 is what I am referring too here. Have a look at the page head, it says: "ISAAKiel/r_tutorial_caa_2018". This thread is an issue to that particular script :-) 

The script runs perfectly until the series of Monte Carlo simulations is computed via the bootstrap command, which fails. I am not sure which bootstrap package you were using but I guess you used package "bootstrap" as it contains the function bootstrap() that is used in the script. Unfortunately bootstrap() ends with an error in the given processing outline...

**Comment by MartinHinz** [comment]
Damn, this happens if you read your issues (not careful enough, thought it comes from oxcAAR) in your email program. Sorry for that!

Actually, the bootstrap command comes from the broom package, not from the "bootstrap" package. Might try this one?

**Comment by vogelso** [comment]
That's it. Works like a charm!

You should mention in the script that the broom package is used to avoid others running into the same issue. 

Thanks a lot for your quick response and the immediate help!

**Comment by MartinHinz** [comment]
Thank you for the proposal, did that. I consider than this issue as closed.

**Comment by vogelso** [comment]
Some people (like me :-) may overlook the comment on the package in the description. How about also providing the broom package directly in the script like `broom::bootstrap(10)`

**Comment by MartinHinz** [comment]
agreed and included. Thanks again!

**Comment by vogelso** [comment]
Perfect! thanks and good bye
